export const mas = [
    {
        id: 1,
        title: "Фильм 1",
        description: "Описание фильма 1",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 2,
        title: "Фильм 2",
        description: "Описание фильма 2",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 3,
        title: "Фильм 3",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
      {
        id: 4,
        title: "Фильм 4",
        description: "Описание фильма 3",
        imageUrl: "https://via.placeholder.com/300x400",
        count: 20,
      },
]